In [ ]:
# Gauri Bankar               TE_B_06


# Title: Data Analytics III

# 1. Implement simple Naive Bayes Classification algorithm using Python on iris.csv dataset.
# 2. Compute Confusion matrix to find TP, FP, TN, FN, Accuracy,Error rate, Precision, Recall on the given dataset.


In [1]:
# Importing Libraries
import numpy as np
import pandas as pd


In [16]:
df=pd.read_csv("Iris.csv")


In [17]:
df.head()


Id  SepalLengthCm  SepalWidthCm  PetalLengthCm  PetalWidthCm      Species
0   1            5.1           3.5            1.4           0.2  Iris-setosa
1   2            4.9           3.0            1.4           0.2  Iris-setosa
2   3            4.7           3.2            1.3           0.2  Iris-setosa
3   4            4.6           3.1            1.5           0.2  Iris-setosa
4   5            5.0           3.6            1.4           0.2  Iris-setosa

In [18]:
df.replace(["Iris-setosa","Iris-versicolor","Iris-virginica"],[1,2,3], inplace=True)
df.head()


Id  SepalLengthCm  SepalWidthCm  PetalLengthCm  PetalWidthCm  Species
0   1            5.1           3.5            1.4           0.2        1
1   2            4.9           3.0            1.4           0.2        1
2   3            4.7           3.2            1.3           0.2        1
3   4            4.6           3.1            1.5           0.2        1
4   5            5.0           3.6            1.4           0.2        1

In [19]:
#Spliting the dataset in independent and dependent variables
x = df.iloc[:,:4]
y = df["Species"].values


In [20]:
x.head()


Id  SepalLengthCm  SepalWidthCm  PetalLengthCm
0   1            5.1           3.5            1.4
1   2            4.9           3.0            1.4
2   3            4.7           3.2            1.3
3   4            4.6           3.1            1.5
4   5            5.0           3.6            1.4

In [22]:
y


array([1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1,
       1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1,
       1, 1, 1, 1, 1, 1, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2,
       2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2,
       2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 3, 3, 3, 3, 3, 3, 3, 3, 3, 3,
       3, 3, 3, 3, 3, 3, 3, 3, 3, 3, 3, 3, 3, 3, 3, 3, 3, 3, 3, 3, 3, 3,
       3, 3, 3, 3, 3, 3, 3, 3, 3, 3, 3, 3, 3, 3, 3, 3, 3, 3])

In [23]:
# Splitting the dataset into the Training set and Test set
# We will use 80% of the data for training and then test our model on the 20% held out for that purpose. 
# Scikit-learn contains a function that will randomly split the dataset for us into training and test sets. 

from sklearn.model_selection import train_test_split

x_train, x_test, y_train, y_test = train_test_split(x, y, test_size = 0.2)


In [24]:
 # Use Gaussian NB to create model

from sklearn.naive_bayes import GaussianNB
gaussian= GaussianNB()


In [25]:
gaussian.fit(x_train,y_train)


GaussianNB()

In [27]:
# predicting the test set results
y_pred = gaussian.predict(x_test)
y_pred


array([3, 2, 2, 2, 2, 1, 2, 2, 3, 1, 2, 1, 3, 3, 3, 3, 2, 2, 1, 1, 1, 1,
       3, 3, 1, 2, 3, 3, 1, 1])

In [28]:
from sklearn.metrics import confusion_matrix,classification_report
cm = confusion_matrix(y_test, y_pred)
cm


array([[10,  0,  0],
       [ 0,  9,  0],
       [ 0,  1, 10]])

In [29]:
print('true negatives (TN):  ', cm[0,0])
print('true positives (TP):  ', cm[1,1])
print('false positives (FP): ', cm[0,1])
print('false negative (FN):  ', cm[1,0])


true negatives (TN):   10
true positives (TP):   9
false positives (FP):  0
false negative (FN):   0


In [30]:
from sklearn.metrics import accuracy_score ,precision_score,recall_score
accuracy = accuracy_score(y_test,y_pred)
precision =precision_score(y_test, y_pred,average='micro')
recall =  recall_score(y_test, y_pred,average='micro')


In [32]:
print("Accuracy: ",accuracy)
print("Precision: ",precision)
print("Recall: ",recall)


Accuracy:  0.9666666666666667
Precision:  0.9666666666666667
Recall:  0.9666666666666667


In [33]:
cl_report=classification_report(y_test,y_pred)
print(cl_report)


              precision    recall  f1-score   support

           1       1.00      1.00      1.00        10
           2       0.90      1.00      0.95         9
           3       1.00      0.91      0.95        11

    accuracy                           0.97        30
   macro avg       0.97      0.97      0.97        30
weighted avg       0.97      0.97      0.97        30

